### ISSUE TITLE
Update PiUSB.dll

### ISSUE THREAD

**Issue by dscho** [openspim/micromanager#2]
Please download http://picard-industries.com/software/usb-4d-stage.zip and use it. Apparently, there is a slight change: it uses the C, rather than the C++ convention for linking. All it means for us is that we have to re-compile our code.

**Comment by stuyvenberg** [comment]
A byte-for-byte comparison via hex editor confirmed that all binaries, libraries, definition files, and headers were identical. We are currently using the latest version of the code.

However, our 3rdpartypublic mirror still contains the old files as well. (They are not being used by our project, but might confuse the issue.) They will be removed.

**Comment by dscho** [comment]
When updating, it is good practice to replace the old files. Thank you for making it so.
