### ISSUE TITLE
Update Picard .dll files

### ISSUE THREAD

**Issue by dscho** [openspim/micromanager#4]
@hkmoon you said you have a Windows dev box? Could we give this a hand together?

**Comment by hkmoon** [comment]
@dscho I sent a mail for your MPI account.

**Comment by dscho** [comment]
Sorry, won't make it before noon!

**Comment by dscho** [comment]
Oh shucks. Administrative errands always take 3x as long as one thinks. :frown:

**Comment by hkmoon** [comment]
I round-tripped the 3rd floor already. 
Hopefully, the administrative works will be finished before noon. 

When you come to the institute, send me a msg then. Let’s do it with coffee.

**Comment by dscho** [comment]
I am here! (Atrium)

**Comment by hkmoon** [comment]
OK, see you soon!!

**Comment by dscho** [comment]
Whoops, forgot to update this ticket: I already tested on a physical setup, contributed the changes, and they were accepted into 1.4.21!
